[package]
name = "tracing-gelf"
version = "0.1.0"
authors = ["Harry  Barber <hlbarber93@gmail.com>"]
edition = "2018"

[dependencies]
hostname = "0.3.0"
serde_json = "1.0.44"
tokio = { version = "0.2.5", features = ["tcp"] }
tracing-core = "0.1.7"
tracing-subscriber = "0.2.0-alpha.2"
tracing-serde = "0.1.0"

[dev-dependencies]
tokio = { version = "0.2.5", features = ["macros"] }
tracing = "0.1.10"
